// flow-typed signature: 4fec7e5ab1143c007d07f54dfd707149
// flow-typed version: <<STUB>>/react-automata_v^2.0.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-automata'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-automata' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-automata/lib/Action' {
  declare module.exports: any;
}

declare module 'react-automata/lib/createConditional' {
  declare module.exports: any;
}

declare module 'react-automata/lib/index' {
  declare module.exports: any;
}

declare module 'react-automata/lib/State' {
  declare module.exports: any;
}

declare module 'react-automata/lib/testStatechart' {
  declare module.exports: any;
}

declare module 'react-automata/lib/utils' {
  declare module.exports: any;
}

declare module 'react-automata/lib/withStatechart' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-automata/lib/Action.js' {
  declare module.exports: $Exports<'react-automata/lib/Action'>;
}
declare module 'react-automata/lib/createConditional.js' {
  declare module.exports: $Exports<'react-automata/lib/createConditional'>;
}
declare module 'react-automata/lib/index.js' {
  declare module.exports: $Exports<'react-automata/lib/index'>;
}
declare module 'react-automata/lib/State.js' {
  declare module.exports: $Exports<'react-automata/lib/State'>;
}
declare module 'react-automata/lib/testStatechart.js' {
  declare module.exports: $Exports<'react-automata/lib/testStatechart'>;
}
declare module 'react-automata/lib/utils.js' {
  declare module.exports: $Exports<'react-automata/lib/utils'>;
}
declare module 'react-automata/lib/withStatechart.js' {
  declare module.exports: $Exports<'react-automata/lib/withStatechart'>;
}
