// flow-typed signature: 94e6d68ce213be296e303359b38676db
// flow-typed version: <<STUB>>/relay_v^0.8.0-1/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'relay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'relay' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'relay/relay' {
  declare module.exports: any;
}

declare module 'relay/test/buster' {
  declare module.exports: any;
}

declare module 'relay/test/chain-test' {
  declare module.exports: any;
}

declare module 'relay/test/combine-test' {
  declare module.exports: any;
}

declare module 'relay/test/parallel-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'relay/relay.js' {
  declare module.exports: $Exports<'relay/relay'>;
}
declare module 'relay/test/buster.js' {
  declare module.exports: $Exports<'relay/test/buster'>;
}
declare module 'relay/test/chain-test.js' {
  declare module.exports: $Exports<'relay/test/chain-test'>;
}
declare module 'relay/test/combine-test.js' {
  declare module.exports: $Exports<'relay/test/combine-test'>;
}
declare module 'relay/test/parallel-test.js' {
  declare module.exports: $Exports<'relay/test/parallel-test'>;
}
